### ISSUE TITLE
Add a "training" variable for audios not to keep ?

### ISSUE THREAD

**Issue by hugolpz** [0x010C/LinguaRecorder#2]
Suddenly thinking, it could be good to have a checkbox and variable "training" for audios which are not intended to be kept nor to shared around.

**Use case:** Half of my recordings so far have been made when training people. These recordings are done in noisy rooms, people talking around, and/or with poor hardware. I constantly worry this recordings could spread around and pollute the final dataset by my user.

**Comment by 0x010C** [comment]
The Recorder object only manage the recording part. After it has stopped, it will return an AudioRecord object containing the recorded sound. It's then free to the developper who use the library to do whatever he want with it (send it to an API, play it, download it, or abandon it in the absolute emptiness).

**Comment by hugolpz** [comment]
Ok, thanks. I'am getting your approach and scope thanks to your answer.s. :+1:
